name: Run Flask Tests

on:
  push:
    branches:
      - main  # Runs on pushes to main
  pull_request:
    branches:
      - main  # Runs on PRs targeting main

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    services:
      postgres:
        image: postgres:13  # Using PostgreSQL if needed
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U testuser -d testdb"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Up Database
        run: |
          export FLASK_APP=app/server.py
          flask db upgrade || echo "Skipping Flask migrations"

      - name: Run Tests with Pytest
        env:
          SECRET_KEY: "test_secret"  # Mock secret key
          SQLALCHEMY_DATABASE_URI: "sqlite:///:memory:"  # In-memory SQLite for testing
        run: |
          source venv/bin/activate
          pytest --maxfail=1 --disable-warnings --tb=short
